language:
  - python

python:
  - "2.6"
  - "2.7"

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq libgdal1h
 - sudo apt-get install -y python-qt4 python-qgis pylint

script:
  - make lint
